Switch menu-button to FA icon
TuxedoTako/4chan-xt pull request #68
Opened 2024-05-31 09:09 UTC by saxamaphone69

Switches the `🞃` used for `menu-button` to its Font Awesome icon equivalent, `caret-down`, as `🞃` does not render on macOS/iOS. I should note that 4chan X used `chevron-down`/`angle-down` - so up to you if you want to switch to that.

This would count as a continuation of #38, and also fixes some of the poor alignment with CSS.
For reference, here's what it looks like:
![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/cfd64bae-5ec6-4054-a8ec-46e736422c51)

Not sure if switching all the other icons (e.g. close unicode icons, CSS icons in the gallery and menu icon in the header) to the FA icons is something you'd be interested in @TuxedoTako, [as per my original PR on 4chan X](https://github.com/ccd0/4chan-x/pull/2395).

2024-05-31 15:00 UTC, TuxedoTako requested changes
What is preventing you from creating a local test build? 

- Just get [node](https://nodejs.org/en/download/prebuilt-installer) if you don't have that yet, it includes npm. 
- Then open a terminal in your 4chan XT directory.
- Run `npm install` to get the dependencies.
- Run `npm run build`.

2024-05-31 15:00 UTC, TuxedoTako commented on src/Menu/Menu.js
> +import Iocn from "../Icons/icon";
You spelled Icon wrong.

![image](https://github.com/TuxedoTako/4chan-xt/assets/126348645/af5ab39a-9b12-49fc-8f8e-b8576c503599)

What editor are you using? VS code warns about this:

![Code_8JZvQV24ns](https://github.com/TuxedoTako/4chan-xt/assets/126348645/39f08d39-e7e1-4264-b56a-ce64ee92466f) (spell checker is an extension)
![Code_oVnv70eCR4](https://github.com/TuxedoTako/4chan-xt/assets/126348645/9a6eb12f-cb87-488f-a544-c5a7dd7ca051)

2024-05-31 20:09 UTC, saxamaphone69 commented
I get the npm build stuff and did the little play button like you mentioned last time. I use vscode on my MacBook because I could work it out on Windows. It’s the git stuff I have no clue about.

2024-05-31 20:13 UTC, saxamaphone69 commented
See like I’m sure there is a way to squash or have redo that commit, but no clue.
I don’t know how to make a fork of your fork, make a branch of that fork, pull any changes you’ve made so I have the latest, and then create a pull request.
I know what I need to do, just don’t know how to actually do it.

2024-06-01 09:51 UTC, TuxedoTako commented
The reason I asked about your build is because you mentioned having trouble with building: https://github.com/TuxedoTako/4chan-xt/issues/60#issuecomment-2119210646, and your change resulting in error messages when just opening a thread, leading me to believe you didn't test locally.

>See like I’m sure there is a way to squash or have redo that commit, but no clue.

I think the thing you're looking for is an "interactive rebase", but doing that on a branch you already pushed to github involves `git push --force`.  Anyway, since you want the commits squashed, I'll just do a squash and merge on github.

>I don’t know how to make a fork of your fork, make a branch of that fork, pull any changes you’ve made so I have the latest, and then create a pull request.

What do you mean? All your pull requests are correctly created from the latest project-XT branch?

2024-06-01 09:51 UTC, merged

2024-06-01 10:49 UTC, saxamaphone69 commented
I'm stumbling in the dark and got lucky with where I stepped, I guess.

Thanks for merging. If I find something else, I'll try my best.